version: '3'
services:
  db:
    image: mysql
    container_name: db
    entrypoint: ['docker-entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password

  api:
    container_name: api
    tty: true
    stdin_open: true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/var/www/app
      - /home/$USER/.api.bash_history:/root/.bash_history
    ports:
      - "3000:3000"
    depends_on:
      - db
